"""decision_system_tables

Revision ID: 2e5ae275617d
Revises: a8c0d2e4f6b7
Create Date: 2026-04-10 16:10:03.031689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e5ae275617d'
down_revision: Union[str, Sequence[str], None] = 'a8c0d2e4f6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_activities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division_code', sa.String(length=20), nullable=False),
    sa.Column('division_name', sa.String(length=255), nullable=True),
    sa.Column('expected_unit', sa.String(length=20), nullable=True),
    sa.Column('scope_family', sa.String(length=100), nullable=True),
    sa.Column('typical_cost_bucket', sa.String(length=50), nullable=True),
    sa.Column('common_dependencies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('comparable_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('final_contract_value', sa.Float(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('market_sector', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('delivery_method', sa.String(length=50), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('size_sf', sa.Float(), nullable=True),
    sa.Column('scope_types', sa.Text(), nullable=True),
    sa.Column('complexity_level', sa.String(length=20), nullable=True),
    sa.Column('schedule_pressure', sa.String(length=20), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_aliases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_activity_id', sa.String(length=36), nullable=False),
    sa.Column('alias', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['canonical_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_actuals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparable_project_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_activity_name', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('actual_unit_cost', sa.Float(), nullable=True),
    sa.Column('actual_total_cost', sa.Float(), nullable=True),
    sa.Column('actual_production_rate', sa.Float(), nullable=True),
    sa.Column('variance_to_estimate', sa.Float(), nullable=True),
    sa.Column('cost_code', sa.String(length=50), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['comparable_project_id'], ['comparable_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historical_rate_observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparable_project_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_activity_id', sa.String(length=36), nullable=True),
    sa.Column('raw_activity_name', sa.String(length=500), nullable=False),
    sa.Column('division_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('labor_rate', sa.Float(), nullable=True),
    sa.Column('material_rate', sa.Float(), nullable=True),
    sa.Column('equipment_rate', sa.Float(), nullable=True),
    sa.Column('subcontract_rate', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('equipment_cost', sa.Float(), nullable=True),
    sa.Column('sub_cost', sa.Float(), nullable=True),
    sa.Column('production_rate', sa.Float(), nullable=True),
    sa.Column('production_rate_unit', sa.String(length=50), nullable=True),
    sa.Column('observation_date', sa.Date(), nullable=True),
    sa.Column('recency_weight', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('quality_weight', sa.Float(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['canonical_activities.id'], ),
    sa.ForeignKeyConstraint(['comparable_project_id'], ['comparable_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('run_status', sa.String(length=30), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('context_snapshot', sa.Text(), nullable=True),
    sa.Column('source_package_id', sa.Integer(), nullable=True),
    sa.Column('total_direct_cost', sa.Float(), nullable=True),
    sa.Column('total_indirect_cost', sa.Float(), nullable=True),
    sa.Column('total_risk', sa.Float(), nullable=True),
    sa.Column('total_escalation', sa.Float(), nullable=True),
    sa.Column('total_fee', sa.Float(), nullable=True),
    sa.Column('final_bid_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_package_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section_label', sa.String(length=255), nullable=True),
    sa.Column('snippet_text', sa.Text(), nullable=True),
    sa.Column('bounding_box_json', sa.Text(), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid_outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('final_bid_submitted', sa.Float(), nullable=True),
    sa.Column('winning_bid_value', sa.Float(), nullable=True),
    sa.Column('delta_to_winner', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_breakdown_buckets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('bucket_type', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escalation_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('base_index', sa.Float(), nullable=True),
    sa.Column('escalation_rate', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('procurement_date', sa.Date(), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('escalation_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('planned_duration_days', sa.Integer(), nullable=True),
    sa.Column('aggressive_duration_days', sa.Integer(), nullable=True),
    sa.Column('conservative_duration_days', sa.Integer(), nullable=True),
    sa.Column('labor_loading_factor', sa.Float(), nullable=True),
    sa.Column('gc_duration_factor', sa.Float(), nullable=True),
    sa.Column('acceleration_cost', sa.Float(), nullable=True),
    sa.Column('schedule_risk_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('canonical_activity_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('division_code', sa.String(length=20), nullable=True),
    sa.Column('work_package', sa.String(length=100), nullable=True),
    sa.Column('activity_family', sa.String(length=100), nullable=True),
    sa.Column('scope_status', sa.String(length=30), nullable=True),
    sa.Column('inclusion_confidence', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['canonical_activities.id'], ),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benchmark_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=True),
    sa.Column('canonical_activity_id', sa.String(length=36), nullable=True),
    sa.Column('comparable_filter_json', sa.Text(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('p10', sa.Float(), nullable=True),
    sa.Column('p25', sa.Float(), nullable=True),
    sa.Column('p50', sa.Float(), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('p90', sa.Float(), nullable=True),
    sa.Column('mean', sa.Float(), nullable=True),
    sa.Column('std_dev', sa.Float(), nullable=True),
    sa.Column('context_similarity_score', sa.Float(), nullable=True),
    sa.Column('benchmark_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_label', sa.String(length=20), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_activity_id'], ['canonical_activities.id'], ),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_risk_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('impact_cost', sa.Float(), nullable=True),
    sa.Column('impact_time_days', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('linked_scope_item_id', sa.String(length=36), nullable=True),
    sa.Column('source_reference_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.ForeignKeyConstraint(['linked_scope_item_id'], ['scope_items.id'], ),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quantity_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_reference_id', sa.String(length=36), nullable=True),
    sa.Column('quantity_confidence', sa.Float(), nullable=True),
    sa.Column('missing_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scope_item_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=False),
    sa.Column('source_reference_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_type', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ),
    sa.ForeignKeyConstraint(['source_reference_id'], ['source_references.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decision_estimate_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('scope_item_id', sa.String(length=36), nullable=True),
    sa.Column('benchmark_result_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('division_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('recommended_unit_cost', sa.Float(), nullable=True),
    sa.Column('recommended_total_cost', sa.Float(), nullable=True),
    sa.Column('estimator_unit_cost', sa.Float(), nullable=True),
    sa.Column('estimator_total_cost', sa.Float(), nullable=True),
    sa.Column('pricing_basis', sa.String(length=50), nullable=True),
    sa.Column('benchmark_sample_size', sa.Integer(), nullable=True),
    sa.Column('benchmark_p25', sa.Float(), nullable=True),
    sa.Column('benchmark_p50', sa.Float(), nullable=True),
    sa.Column('benchmark_p75', sa.Float(), nullable=True),
    sa.Column('benchmark_p90', sa.Float(), nullable=True),
    sa.Column('benchmark_mean', sa.Float(), nullable=True),
    sa.Column('benchmark_std_dev', sa.Float(), nullable=True),
    sa.Column('benchmark_context_similarity', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('line_status', sa.String(length=30), nullable=True),
    sa.Column('missing_quantity', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['benchmark_result_id'], ['benchmark_results.id'], ),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.ForeignKeyConstraint(['scope_item_id'], ['scope_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimator_overrides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('estimate_run_id', sa.String(length=36), nullable=False),
    sa.Column('estimate_line_id', sa.String(length=36), nullable=False),
    sa.Column('original_value', sa.Float(), nullable=False),
    sa.Column('overridden_value', sa.Float(), nullable=False),
    sa.Column('override_type', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=50), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_line_id'], ['decision_estimate_lines.id'], ),
    sa.ForeignKeyConstraint(['estimate_run_id'], ['estimate_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_actuals_line_items', schema=None) as batch_op:
        batch_op.drop_index('ix_fa_li_project_id')
        batch_op.create_index(batch_op.f('ix_field_actuals_line_items_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('market_sector', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('scope_types', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('contract_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('complexity_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('schedule_pressure', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('bid_due_date', sa.String(length=50), nullable=True))

    with op.batch_alter_table('takeoff_items_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_takeoff_items_v2_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('takeoff_items_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_takeoff_items_v2_id'))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('bid_due_date')
        batch_op.drop_column('schedule_pressure')
        batch_op.drop_column('complexity_level')
        batch_op.drop_column('contract_type')
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('scope_types')
        batch_op.drop_column('market_sector')
        batch_op.drop_column('region')

    with op.batch_alter_table('field_actuals_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_actuals_line_items_project_id'))
        batch_op.create_index('ix_fa_li_project_id', ['project_id'], unique=False)

    op.drop_table('estimator_overrides')
    op.drop_table('decision_estimate_lines')
    op.drop_table('scope_item_evidence')
    op.drop_table('quantity_items')
    op.drop_table('decision_risk_items')
    op.drop_table('benchmark_results')
    op.drop_table('scope_items')
    op.drop_table('schedule_scenarios')
    op.drop_table('escalation_inputs')
    op.drop_table('cost_breakdown_buckets')
    op.drop_table('bid_outcomes')
    op.drop_table('source_references')
    op.drop_table('estimate_runs')
    op.drop_table('historical_rate_observations')
    op.drop_table('field_actuals')
    op.drop_table('activity_aliases')
    op.drop_table('comparable_projects')
    op.drop_table('canonical_activities')
    # ### end Alembic commands ###
