"""add_cache_and_sprint6_columns

Revision ID: 37e85ea73069
Revises: ee412a823a92
Create Date: 2026-03-25 18:04:40.918119

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "37e85ea73069"
down_revision: str | Sequence[str] | None = "ee412a823a92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
