"""add_estimated_cost_to_agent_run_log

Revision ID: e4ae649389b5
Revises: e5a2b7d3f1c8
Create Date: 2026-03-31 14:30:39.937618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ae649389b5'
down_revision: Union[str, Sequence[str], None] = 'e5a2b7d3f1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.drop_column('estimated_cost')

    # ### end Alembic commands ###
