"""initial_schema_sprint7

Revision ID: ee412a823a92
Revises: 
Create Date: 2026-03-25 18:03:21.765276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee412a823a92'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('supplier', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_prices_csi_code'), ['csi_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_prices_id'), ['id'], unique=False)

    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)

    op.create_table('productivity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=False),
    sa.Column('crew_type', sa.String(length=100), nullable=True),
    sa.Column('productivity_rate', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('source_project', sa.String(length=255), nullable=True),
    sa.Column('source_project_id', sa.Integer(), nullable=True),
    sa.Column('is_actual', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productivity_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productivity_history_csi_code'), ['csi_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_productivity_history_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_number', sa.String(length=100), nullable=False),
    sa.Column('project_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('square_footage', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('bid_date', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_number')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)

    op.create_table('agent_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_run_logs_id'), ['id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('processing_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    op.create_table('estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('total_direct_cost', sa.Float(), nullable=True),
    sa.Column('total_labor_cost', sa.Float(), nullable=True),
    sa.Column('total_material_cost', sa.Float(), nullable=True),
    sa.Column('total_subcontractor_cost', sa.Float(), nullable=True),
    sa.Column('gc_markup_pct', sa.Float(), nullable=True),
    sa.Column('gc_markup_amount', sa.Float(), nullable=True),
    sa.Column('overhead_pct', sa.Float(), nullable=True),
    sa.Column('overhead_amount', sa.Float(), nullable=True),
    sa.Column('profit_pct', sa.Float(), nullable=True),
    sa.Column('profit_amount', sa.Float(), nullable=True),
    sa.Column('contingency_pct', sa.Float(), nullable=True),
    sa.Column('contingency_amount', sa.Float(), nullable=True),
    sa.Column('total_bid_amount', sa.Float(), nullable=True),
    sa.Column('exclusions', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('alternates', sa.JSON(), nullable=True),
    sa.Column('bid_bond_required', sa.Integer(), nullable=True),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('variance_report_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimates_id'), ['id'], unique=False)

    op.create_table('gap_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('total_gaps', sa.Integer(), nullable=True),
    sa.Column('critical_count', sa.Integer(), nullable=True),
    sa.Column('moderate_count', sa.Integer(), nullable=True),
    sa.Column('watch_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_reports_id'), ['id'], unique=False)

    op.create_table('project_actuals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_quantity', sa.Float(), nullable=True),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.Column('estimated_labor_hours', sa.Float(), nullable=True),
    sa.Column('actual_labor_hours', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('variance_hours', sa.Float(), nullable=True),
    sa.Column('variance_cost', sa.Float(), nullable=True),
    sa.Column('variance_pct', sa.Float(), nullable=True),
    sa.Column('crew_type', sa.String(length=100), nullable=True),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_actuals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_actuals_id'), ['id'], unique=False)

    op.create_table('upload_sessions',
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('next_chunk', sa.Integer(), nullable=False),
    sa.Column('temp_dir', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('upload_id')
    )
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_upload_sessions_upload_id'), ['upload_id'], unique=False)

    op.create_table('estimate_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=False),
    sa.Column('division_number', sa.String(length=10), nullable=False),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('material_cost', sa.Float(), nullable=True),
    sa.Column('equipment_cost', sa.Float(), nullable=True),
    sa.Column('subcontractor_cost', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('estimate_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_estimate_line_items_id'), ['id'], unique=False)

    op.create_table('gap_report_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gap_report_id', sa.Integer(), nullable=False),
    sa.Column('division_number', sa.String(length=10), nullable=False),
    sa.Column('section_number', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('gap_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gap_report_id'], ['gap_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gap_report_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gap_report_items_id'), ['id'], unique=False)

    op.create_table('spec_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('division_number', sa.String(length=10), nullable=False),
    sa.Column('section_number', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('work_description', sa.Text(), nullable=True),
    sa.Column('materials_referenced', sa.JSON(), nullable=True),
    sa.Column('execution_requirements', sa.Text(), nullable=True),
    sa.Column('submittal_requirements', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spec_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spec_sections_id'), ['id'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('agent_number', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_creation_tokens', sa.Integer(), nullable=True),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_project_id'), ['project_id'], unique=False)

    op.create_table('upload_chunks',
    sa.Column('upload_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('chunk_data', sa.LargeBinary(), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_sessions.upload_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upload_id', 'chunk_number')
    )
    op.create_table('takeoff_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('spec_section_id', sa.Integer(), nullable=True),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=50), nullable=False),
    sa.Column('drawing_reference', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_manual_override', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['spec_section_id'], ['spec_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('takeoff_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_takeoff_items_id'), ['id'], unique=False)

    op.create_table('labor_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('takeoff_item_id', sa.Integer(), nullable=False),
    sa.Column('csi_code', sa.String(length=20), nullable=False),
    sa.Column('work_type', sa.String(length=100), nullable=True),
    sa.Column('crew_type', sa.String(length=100), nullable=True),
    sa.Column('productivity_rate', sa.Float(), nullable=False),
    sa.Column('productivity_unit', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('labor_hours', sa.Float(), nullable=False),
    sa.Column('crew_size', sa.Integer(), nullable=True),
    sa.Column('crew_days', sa.Float(), nullable=True),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('total_labor_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['takeoff_item_id'], ['takeoff_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('labor_estimates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_labor_estimates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('labor_estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_labor_estimates_id'))

    op.drop_table('labor_estimates')
    with op.batch_alter_table('takeoff_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_takeoff_items_id'))

    op.drop_table('takeoff_items')
    op.drop_table('upload_chunks')
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_project_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_id'))

    op.drop_table('token_usage')
    with op.batch_alter_table('spec_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spec_sections_id'))

    op.drop_table('spec_sections')
    with op.batch_alter_table('gap_report_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_report_items_id'))

    op.drop_table('gap_report_items')
    with op.batch_alter_table('estimate_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimate_line_items_id'))

    op.drop_table('estimate_line_items')
    with op.batch_alter_table('upload_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_sessions_upload_id'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_upload_sessions_expires_at'))

    op.drop_table('upload_sessions')
    with op.batch_alter_table('project_actuals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_actuals_id'))

    op.drop_table('project_actuals')
    with op.batch_alter_table('gap_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gap_reports_id'))

    op.drop_table('gap_reports')
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_estimates_id'))

    op.drop_table('estimates')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))

    op.drop_table('documents')
    with op.batch_alter_table('agent_run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_run_logs_id'))

    op.drop_table('agent_run_logs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_id'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('productivity_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productivity_history_id'))
        batch_op.drop_index(batch_op.f('ix_productivity_history_csi_code'))

    op.drop_table('productivity_history')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    with op.batch_alter_table('material_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_prices_id'))
        batch_op.drop_index(batch_op.f('ix_material_prices_csi_code'))

    op.drop_table('material_prices')
    # ### end Alembic commands ###
